{{- if .Values.rbac.psp.enabled }}
apiVersion: {{ default (include "psp.apiVersion" .) .Values.rbac.psp.apiVersion }}
kind: PodSecurityPolicy
metadata:
  name: {{ template "vector.fullname" . }}
spec:
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'hostPath'
    - 'configMap'
    - 'secret'
  allowedHostPaths:
    - pathPrefix: "/var/log"
      readOnly: true
    - pathPrefix: "/var/lib/docker/containers"
      readOnly: true
    {{- range .Values.extraVolumes }}
    {{- if .hostPath }}
    - pathPrefix: {{ .hostPath.path }}
    {{- end }}
    {{- end }}
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
{{- end }}
{{- end }}
